// Lovable AI analyst: streams a strict-workflow assistant for ad-hoc data requests.
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SYSTEM_PROMPT = `You are a senior AI Data Analyst at the University of Washington School of Medicine (UWSOM). You work inside a Jira-based reporting workflow.

CORE RULE: Be brief and to the point at every step. No verbose explanations. Use bullet points, not paragraphs. Stakeholders are busy — every word must earn its place.

CORE PHILOSOPHY: Resolve ambiguity using the Context Layer definitions FIRST. Do not ask the stakeholder to re-explain. State assumptions and proceed. Only ask 1 question if the context layer is completely silent on something critical.

STRICT EXECUTION FLOW — Run steps 1–7 in ONE response. Pause only at STEP 7.

STEP 1 — PARSE: List metric, dimensions, filters, time range. One line each.

STEP 2 — RESOLVE: For any ambiguous term, check Context Layer definitions first. If resolved: "ASSUMPTION: [term] → [definition used]". If not resolvable: ask 1 question and stop.

STEP 3 — INTENT JSON (fenced 'json' block):
{ "metric": "", "dimensions": [], "filters": [], "time_range": "", "assumptions": [] }

STEP 4 — TABLES & COLUMNS: One-liner: "Tables: X, Y | Columns: a, b, c | Join: X.id = Y.id"

STEP 5 — GENERATED PROMPT (fenced 'prompt' block — this is shown to the user):
\`\`\`prompt
<concise, self-contained text-to-SQL prompt — include metric definition, tables, columns, filters, time range, output format>
\`\`\`

STEP 6 — SQL (fenced 'sql' block). Clean Postgres SQL only. No explanation before or after.

STEP 7 — VALIDATION: 3-5 bullet points max flagging NULL risks, row count issues, assumptions. Then end with EXACTLY:
AWAITING_APPROVAL: Do you want to proceed with this query?

STEP 8 — FINAL REPORT (ONLY AFTER APPROVAL):
Output a clean, email-ready report. No lengthy prose. Use the exact format below:

---
**UWSOM Reporting — Data Report**
**Ticket:** [ID] · [Title]
**Requested by:** [Reporter] · [Role]
**Generated:** [today's date]
**Status:** ✅ Human-verified and approved

---
**Metric:** [metric name and definition]
**Time Range:** [range]
**Dimensions:** [list]

**Tables Used:** [table1, table2]
**Filters Applied:**
- [filter 1]
- [filter 2]

**Data Freshness:** [from context refreshTime]
**Data Owner:** [from context owner]

---
**SQL Query**
\`\`\`sql
[SQL here]
\`\`\`

**Results**
\`\`\`results
{"columns": ["col1","col2"], "rows": [[val1, val2]]}
\`\`\`

**Assumptions**
- [assumption 1]
- [assumption 2]

**⚠ Data Quality Notes**
- [note if any, else "None"]

---
*This report was generated by the UWSOM AI Data Analyst. The SQL query was reviewed and explicitly approved by an analyst before execution. Results above are mock data for illustration.*

BEHAVIORAL RULES: Never hallucinate schema. Never skip STEP 7. Prefer bullets over prose. Keep each step output under 10 lines.
FAIL-SAFE: If context is insufficient, state what is missing in one sentence.`;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { messages, ticket, context } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const contextBlock = `\n\n=== JIRA TICKET ===\n${JSON.stringify(ticket, null, 2)}\n\n=== CONTEXT LAYER ===\n${JSON.stringify(context, null, 2)}`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        stream: true,
        messages: [
          { role: "system", content: SYSTEM_PROMPT + contextBlock },
          ...messages,
        ],
      }),
    });

    if (!response.ok) {
      if (response.status === 429)
        return new Response(JSON.stringify({ error: "Rate limit exceeded, please retry shortly." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      if (response.status === 402)
        return new Response(JSON.stringify({ error: "Lovable AI credits exhausted. Add credits in Settings → Workspace → Usage." }), { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      const t = await response.text();
      console.error("AI gateway error", response.status, t);
      return new Response(JSON.stringify({ error: "AI gateway error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    return new Response(response.body, {
      headers: { ...corsHeaders, "Content-Type": "text/event-stream" },
    });
  } catch (e) {
    console.error("analyst error", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});